package wiki

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// validTypes is the OKF v0.2 + llmwiki type taxonomy, in canonical order.
var validTypes = []string{
	"ADR", "Term", "Constraint", "Spec", "Spike", "State", "Architecture", "Finding", "Source",
}

// RenderIndex renders wiki/index.md: a catalog of every emitted page grouped
// by type directory. Deterministic order (R8.3): type groups alphabetically,
// concepts within a group by slug. The page carries minimal OKF frontmatter
// (type: Source, a producer-defined index page) so `wiki lint` (which walks
// every page under wiki/) passes for it; the frontmatter carries no
// generated.at, keeping the catalog byte-identical across no-op recompiles.
func RenderIndex(concepts []Concept) string {
	groups := map[string][]Concept{}
	for _, c := range concepts {
		dir := TypeDir(c.Type)
		slug := c.ID
		if slug == "" {
			slug = Slugify(c.Title)
		}
		groups[dir] = append(groups[dir], Concept{ID: slug, Type: c.Type, Title: c.Title, Status: c.Status})
	}

	var dirs []string
	for d := range groups {
		dirs = append(dirs, d)
	}
	sort.Strings(dirs)

	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("type: Source\n")
	b.WriteString("title: \"Wiki Index\"\n")
	b.WriteString("---\n\n")
	b.WriteString("# Wiki Index\n")
	for _, d := range dirs {
		cs := groups[d]
		sort.Slice(cs, func(i, j int) bool { return cs[i].ID < cs[j].ID })
		b.WriteString("\n## ")
		b.WriteString(d)
		b.WriteString("\n")
		for _, c := range cs {
			b.WriteString("- [[")
			b.WriteString(c.ID)
			b.WriteString("]] — ")
			b.WriteString(c.Title)
			if c.Status != "" {
				b.WriteString(" (")
				b.WriteString(c.Status)
				b.WriteString(")")
			}
			b.WriteString("\n")
		}
	}
	return b.String()
}

// RenderAgents renders AGENTS.md: the schema layer documenting the type
// taxonomy, the slug rule, and the lint rule. Static and deterministic.
func RenderAgents() string {
	var b strings.Builder
	b.WriteString("# AGENTS\n")
	b.WriteString("\nThis bundle is generated by `skillgrid wiki compile`. Do not hand-edit files under `wiki/`; regenerate instead.\n")

	b.WriteString("\n## Type taxonomy\n")
	b.WriteString("\nEvery page's frontmatter `type` must be one of:\n")
	for _, typ := range validTypes {
		b.WriteString("- `")
		b.WriteString(typ)
		b.WriteString("`\n")
	}
	b.WriteString("\nPages are grouped under `wiki/<type-dir>/`:\n")
	b.WriteString("- `adr/` — ADR\n")
	b.WriteString("- `concepts/` — Term, Constraint\n")
	b.WriteString("- `entities/` — Spec, Spike, State, Architecture, Finding\n")
	b.WriteString("- `research/` — Finding (uncited web research, status: draft)\n")

	b.WriteString("\n## Slug rule\n")
	b.WriteString("\nA page filename (and its `[[wikilink]]` target) is the title slugified: lowercase ASCII alphanumerics joined by single hyphens, no leading or trailing hyphens. Non-ASCII characters are dropped as boundaries; the reserved titles `index` and `log` gain a `page-` prefix to avoid colliding with the bundle's own files.\n")

	b.WriteString("\n## Lint rule\n")
	b.WriteString("\nEvery page must pass the OKF v0.2 conformance gate (`wiki.Conform`), which `skillgrid wiki lint` runs over `wiki/**.md`: the frontmatter `type` key must be present and non-empty, every `sources[]` entry must carry a non-empty `resource`, every timestamp must be absolute UTC ISO 8601 (`…T…Z`), and `status` (if present) must be one of `draft|stable|deprecated`. Link syntax is not linted: `[[wikilinks]]` are the bundle's link model.\n")
	return b.String()
}

// logFrontmatter is the minimal OKF frontmatter for wiki/log.md (type: Source,
// a producer-defined bundle page). It carries no generated.at, so the log is
// append-only and byte-stable on no-op recompiles (R8) while still passing
// `wiki lint`.
const logFrontmatter = "---\ntype: Source\ntitle: \"Wiki Log\"\n---\n\n"

// AppendLog returns the updated wiki/log.md. When changes is empty it returns
// existing unchanged (no-op compile → no log churn, R8). Otherwise it appends
// one dated entry listing every change; an empty existing starts with the log
// frontmatter + "# Log".
func AppendLog(existing string, now time.Time, changes []string) string {
	if len(changes) == 0 {
		return existing
	}
	out := existing
	if out == "" {
		out = logFrontmatter + "# Log\n"
	}
	if !strings.HasSuffix(out, "\n") {
		out += "\n"
	}
	var b strings.Builder
	b.WriteString("\n## ")
	b.WriteString(now.UTC().Format("2006-01-02"))
	b.WriteString(fmt.Sprintf(" — %d change(s)\n", len(changes)))
	for _, ch := range changes {
		b.WriteString("- ")
		b.WriteString(ch)
		b.WriteString("\n")
	}
	return out + b.String()
}
