package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/devopstales/skillgrid/mnemonic/internal/setup"
	"gopkg.in/yaml.v3"
)

// architectureRel is the path of the ARCHITECTURE.md scaffold template inside
// the skill tree.
const architectureRel = ".agents/skills/lifecycle/onboarding/templates/architecture.md"

// architecturePath is overridable in tests (mirrors agentsPreamblePath).
var architecturePath = func(dir string) string {
	return filepath.Join(dir, architectureRel)
}

// archRepoRoot is overridable in tests to bypass the FindRepoRoot fallback.
var archRepoRoot = setup.FindRepoRoot

// archCfg is the subset of config facts the ARCHITECTURE.md renderer fills.
// Everything is optional: an empty field renders as a <detect> placeholder so a
// greenfield init still produces a complete, navigable scaffold.
type archCfg struct {
	Project   string `yaml:"project"`
	Language  string `yaml:"language"`
	Version   string `yaml:"version"`
	Commands  commandsCfg `yaml:"commands"`
	Testing   testingCfg  `yaml:"testing"`
}

// loadArchCfg reuses the onboarding config facts. A missing file yields a zero
// struct (not an error) so init can scaffold <detect> placeholders.
func loadArchCfg(dir string) (archCfg, error) {
	var cfg archCfg
	path := filepath.Join(dir, ".skillgrid", "config.yaml")
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return cfg, nil
	}
	if err != nil {
		return cfg, err
	}
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return cfg, err
	}
	return cfg, nil
}

// loadArchitectureTemplate resolves the scaffold template from the skill tree
// (project tree first, then repo root). Unlike the preamble it does NOT unwrap
// a fence: the scaffold is a full markdown document and the whole file is the
// template body.
func loadArchitectureTemplate(dir string) (template, path string, err error) {
	for _, candidate := range []string{
		architecturePath(dir),
		filepath.Join(archRepoRoot(dir), architectureRel),
	} {
		data, rerr := os.ReadFile(candidate)
		if rerr != nil {
			continue
		}
		return strings.TrimSpace(string(data)), candidate, nil
	}
	return "", "", fmt.Errorf("architecture template not found under %s", architectureRel)
}

// renderArchitecture fills the scaffold's {placeholders} from cfg. {project} and
// {version} fall back to <detect>; {last_updated} is always the current date
// (UTC) so the document is honest about when it was generated.
func renderArchitecture(cfg archCfg, template string) string {
	detect := func(v string) string {
		if strings.TrimSpace(v) == "" {
			return "<detect>"
		}
		return v
	}
	out := strings.ReplaceAll(template, "{project}", detect(cfg.Project))
	out = strings.ReplaceAll(out, "{version}", detect(cfg.Version))
	out = strings.ReplaceAll(out, "{last_updated}", time.Now().UTC().Format("2006-01-02"))
	return out
}

// writeArchitectureFile scaffolds .skillgrid/ARCHITECTURE.md on first init. It
// is idempotent: an existing file is kept (the onboarding agent owns the filled
// sections, just as it owns the ## Skillgrid sentinel block), so re-running init
// with --force does not clobber the real architecture. Returns the written path,
// or "" when a file already existed.
func writeArchitectureFile(dir string) (string, error) {
	path := filepath.Join(dir, ".skillgrid", "ARCHITECTURE.md")
	if _, err := os.Stat(path); err == nil {
		return "", nil // already present — keep the onboarding-rendered version
	} else if !os.IsNotExist(err) {
		return "", err
	}

	tpl, _, err := loadArchitectureTemplate(dir)
	if err != nil {
		tpl = defaultArchTemplate
	}
	cfg, _ := loadArchCfg(dir)
	body := renderArchitecture(cfg, tpl)

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// defaultArchTemplate is the minimal fallback used only when the scaffold
// template cannot be resolved from the skill tree. It keeps init from failing on
// a missing template file; the onboarding agent replaces it with a full render.
const defaultArchTemplate = `# ARCHITECTURE.md

**Project:** {project}
**Version:** {version}
**Last Updated:** {last_updated}

> Generated by skillgrid init. The onboarding agent fills the real sections.
`
